@startuml Manage Hospital (DELETE)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hospital (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hospitals" as routerHospitals
participant "<<controllers>>\n:hospitals" as controllersHospitals
participant "<<model>>\n:Hospital" as modelHospital
database "<<MongoDB>>\n:hospitals" as HospitalsDatabase

client->server ++:req.delete('/hospitals/:id')
server->routerHospitals ++:app.use('/hospitals',hospitals)
routerHospitals -> controllersHospitals ++:deleteHospital(req.params.id)
controllersHospitals->modelHospital ++:findByIdAndDelete(req.params.id)
modelHospital ->HospitalsDatabase ++: deleteOne({_id: req.params.id})
HospitalsDatabase --> modelHospital --: result
controllersHospitals <-- modelHospital --: result
controllersHospitals->client --:response

@enduml

