@startuml Manage Hospital (GET ONE)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hospital (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hospitals" as routerHospitals
participant "<<controllers>>\n:hospitals" as controllersHospitals
participant "<<model>>\n:Hospital" as modelHospital
database "<<MongoDB>>\n:hospitals" as HospitalsDatabase

client->server ++:req.get('/hospitals/:id')
server->routerHospitals ++:app.use('/hospitals',hospitals)
routerHospitals -> controllersHospitals ++:getHospital(req.params.id)
controllersHospitals->modelHospital ++:findById(req.params.id)
modelHospital ->HospitalsDatabase ++: find()
HospitalsDatabase --> modelHospital --: hospital
controllersHospitals <-- modelHospital --:hospital
controllersHospitals->client --:response

@enduml

